SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEEDBACK_ATTACHMENT](
	[FeedbackAttachmentId] [int] IDENTITY(1,1) NOT NULL,
	[FeedbackId] [int] NOT NULL,
	[AttachmentId] [int] NOT NULL,
	[META_Lock] [bit] NOT NULL,
	[USR_Status] [char](1) NOT NULL,
	[USR_LastUpdateUser] [varchar](50) NOT NULL,
	[DBS_LastUpdateDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_CreationDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_LastUpdateUser] [varchar](50) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  CONSTRAINT [UQ_FEEDBACK_ATTACHMENT] UNIQUE CLUSTERED 
(
	[FeedbackId] ASC,
	[AttachmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  CONSTRAINT [PK__FEEDBACK_ATTACHMENT__1A9ADE7C6497E884] PRIMARY KEY NONCLUSTERED 
(
	[FeedbackAttachmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT ((0)) FOR [META_Lock]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT ('A') FOR [USR_Status]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT (suser_sname()) FOR [USR_LastUpdateUser]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT (sysdatetimeoffset()) FOR [DBS_LastUpdateDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT (sysdatetimeoffset()) FOR [DBS_CreationDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ADD  DEFAULT (suser_sname()) FOR [DBS_LastUpdateUser]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK__FEEDBACK_ATTACHMENT__Attachment__68687968] FOREIGN KEY([AttachmentId])
REFERENCES [dbo].[ATTACHMENT] ([AttachmentId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] CHECK CONSTRAINT [FK__FEEDBACK_ATTACHMENT__Attachment__68687968]
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK__FEEDBACK_ATTACHMENT__Feedback__68687968] FOREIGN KEY([FeedbackId])
REFERENCES [dbo].[FEEDBACK] ([FeedbackId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] CHECK CONSTRAINT [FK__FEEDBACK_ATTACHMENT__Feedback__68687968]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TRIG__FEEDBACK_ATTACHMENT__]
    ON [dbo].[FEEDBACK_ATTACHMENT] FOR INSERT, UPDATE AS

   SET NOCOUNT ON

   /*=================================================================
   **  (1)  UPDATE THE LAST USERID AND DATETIME FIELDS AUTOMATICALLY. 
   **================================================================*/
   IF(UPDATE(DBS_CreationDateTime) AND EXISTS (SELECT * FROM inserted i JOIN deleted d ON i.FeedbackAttachmentId = d.FeedbackAttachmentId WHERE i.DBS_CreationDateTime <> d.DBS_CreationDateTime))
   BEGIN 
       RAISERROR ('DBS_CreationDateTime cannot change.', 16, 1);
       ROLLBACK TRAN
   END
   
   UPDATE dbo.FEEDBACK_ATTACHMENT 
      SET DBS_LastUpdateUser     = SYSTEM_USER,
          DBS_LastUpdateDateTime = SYSDATETIMEOFFSET()
     FROM dbo.FEEDBACK_ATTACHMENT D,
          INSERTED I
    WHERE D.FeedbackAttachmentId = I.FeedbackAttachmentId



GO
ALTER TABLE [dbo].[FEEDBACK_ATTACHMENT] ENABLE TRIGGER [TRIG__FEEDBACK_ATTACHMENT__]
GO
