SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEEDBACK_STATUS](
	[FeedbackStatusId] [int] IDENTITY(1,1) NOT NULL,
	[FeedbackStatus] [varchar](50) NOT NULL,
	[META_Lock] [bit] NOT NULL,
	[USR_Status] [char](1) NOT NULL,
	[USR_LastUpdateUser] [varchar](50) NOT NULL,
	[DBS_LastUpdateDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_CreationDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_LastUpdateUser] [varchar](50) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [PK__FEEDBACK_STATUS__8AFACE1A3118447E] PRIMARY KEY CLUSTERED 
(
	[FeedbackStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [UQ_FEEDBACK_STATUS] UNIQUE NONCLUSTERED 
(
	[FeedbackStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__META_Lock__33F4B129]  DEFAULT ((0)) FOR [META_Lock]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__USR_Status__33F4B129]  DEFAULT ('A') FOR [USR_Status]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__USR_LastUp__34E8D562]  DEFAULT (suser_sname()) FOR [USR_LastUpdateUser]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__DBS_LastUp__35DCF99B]  DEFAULT (sysdatetimeoffset()) FOR [DBS_LastUpdateDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__DBS_Creati__36D11DD4]  DEFAULT (sysdatetimeoffset()) FOR [DBS_CreationDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ADD  CONSTRAINT [DF__FEEDBACK_STATUS__DBS_LastUp__37C5420D]  DEFAULT (suser_sname()) FOR [DBS_LastUpdateUser]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[TRIG__FEEDBACK_STATUS__]
    ON [dbo].[FEEDBACK_STATUS] FOR INSERT, UPDATE AS

   SET NOCOUNT ON

   /*=================================================================
   **  (1)  UPDATE THE LAST USERID AND DATETIME FIELDS AUTOMATICALLY. 
   **================================================================*/
   IF(UPDATE(DBS_CreationDateTime) AND EXISTS (SELECT * FROM inserted i JOIN deleted d ON i.FeedbackStatusId = d.FeedbackStatusId WHERE i.DBS_CreationDateTime <> d.DBS_CreationDateTime))
   BEGIN 
       RAISERROR ('DBS_CreationDateTime cannot change.', 16, 1);
       ROLLBACK TRAN
   END
   
   UPDATE dbo.[FEEDBACK_STATUS] 
      SET DBS_LastUpdateUser     = SYSTEM_USER,
          DBS_LastUpdateDateTime = SYSDATETIMEOFFSET()
     FROM dbo.[FEEDBACK_STATUS] D,
          INSERTED I
    WHERE D.FeedbackStatusId = I.FeedbackStatusId



GO
ALTER TABLE [dbo].[FEEDBACK_STATUS] ENABLE TRIGGER [TRIG__FEEDBACK_STATUS__]
GO
