SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEEDBACK_COMMENT](
	[FeedbackCommentId] [int] IDENTITY(1,1) NOT NULL,
	[FeedbackId] [int] NOT NULL,
	[CommentId] [int] NOT NULL,
	[META_Lock] [bit] NOT NULL,
	[USR_Status] [char](1) NOT NULL,
	[USR_LastUpdateUser] [varchar](50) NOT NULL,
	[DBS_LastUpdateDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_CreationDateTime] [datetimeoffset](7) NOT NULL,
	[DBS_LastUpdateUser] [varchar](50) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  CONSTRAINT [UQ_FEEDBACK_COMMENT] UNIQUE CLUSTERED 
(
	[FeedbackId] ASC,
	[CommentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  CONSTRAINT [PK__FEEDBACK_COMMENT__1A9ADE7C6497E884] PRIMARY KEY NONCLUSTERED 
(
	[FeedbackCommentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT ((0)) FOR [META_Lock]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT ('A') FOR [USR_Status]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT (suser_sname()) FOR [USR_LastUpdateUser]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT (sysdatetimeoffset()) FOR [DBS_LastUpdateDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT (sysdatetimeoffset()) FOR [DBS_CreationDateTime]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ADD  DEFAULT (suser_sname()) FOR [DBS_LastUpdateUser]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK__FEEDBACK_COMMENT__Comment__68687968] FOREIGN KEY([CommentId])
REFERENCES [dbo].[COMMENT] ([CommentId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] CHECK CONSTRAINT [FK__FEEDBACK_COMMENT__Comment__68687968]
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK__FEEDBACK_COMMENT__Feedback__68687968] FOREIGN KEY([FeedbackId])
REFERENCES [dbo].[FEEDBACK] ([FeedbackId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] CHECK CONSTRAINT [FK__FEEDBACK_COMMENT__Feedback__68687968]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TRIG__FEEDBACK_COMMENT__]
    ON [dbo].[FEEDBACK_COMMENT] FOR INSERT, UPDATE AS

   SET NOCOUNT ON

   /*=================================================================
   **  (1)  UPDATE THE LAST USERID AND DATETIME FIELDS AUTOMATICALLY. 
   **================================================================*/
   IF(UPDATE(DBS_CreationDateTime) AND EXISTS (SELECT * FROM inserted i JOIN deleted d ON i.FeedbackCommentId = d.FeedbackCommentId WHERE i.DBS_CreationDateTime <> d.DBS_CreationDateTime))
   BEGIN 
       RAISERROR ('DBS_CreationDateTime cannot change.', 16, 1);
       ROLLBACK TRAN
   END
   
   UPDATE dbo.FEEDBACK_COMMENT 
      SET DBS_LastUpdateUser     = SYSTEM_USER,
          DBS_LastUpdateDateTime = SYSDATETIMEOFFSET()
     FROM dbo.FEEDBACK_COMMENT D,
          INSERTED I
    WHERE D.FeedbackCommentId = I.FeedbackCommentId




GO
ALTER TABLE [dbo].[FEEDBACK_COMMENT] ENABLE TRIGGER [TRIG__FEEDBACK_COMMENT__]
GO
